# Endpoint: hola mundo!!!
GET http://127.0.0.1:8000
### Endpoint: hola mundo!!!
POST  http://127.0.0.1:8000/view/user/createticket
Content-Type: application/json
Authorization: token_gestor_1_dWmFp

{
    "title": "Pruebaaa Prrruba",
    "description": "Que salga bien",
    "status": "abierto",
    "userid": 1,
    "adminid": 3
}

### Endpoint: queryallticket
GET  http://127.0.0.1:8000/view/queryallticket

### Endpoint: queryticketbyid
GET  http://127.0.0.1:8000/view/queryallticketbyid
Content-Type: application/json
Authorization: token_admin_3_Aezr6

{
    "gestor_id": 1
}
###Endpoint : creat commitr 
POST  http://127.0.0.1:8000/view/createcommitticet
Content-Type: application/json
Authorization: token_gestor_1_51i4v

{
    "ticket_id": 1,
    "user_id": 2,
    "mensaje": "Que super bien"
}
### Endpoint: Consultar todos los ticketsactividad 
GET  http://127.0.0.1:8000/view/showcommit
Content-Type: application/json
Authorization: token_gestor_1_dWmFp

{
    "ticket_id": 2
}